nornf
ewf.github/ISSUE_TEMPLATE
Update issue temple
_includes
Fix site title attribute logic (#121)
_layouts
feat: include disqus if we enable it
_posts
Add html-proofer script and related fixes
css/font-awesome
Colors can now be set in config file.
img
new design
js
Update contact_me.js
mail
Disable form mail if spambot fills hidden field
.gitignore
added '.jekyll-cache'
2 years ago
.travis.yml
Update Travis script
2 years ago
Gemfile
Update Gemfile
4 years ago
LICENCE
Fixes #85
4 years ago
README.md
Update README.md
2 years ago
Rakefile
Add html-proofer script and related fixes
2 years ago
_config.yml
Add html-proofer script and related fixes
2 years ago
feed.xml
Updated feed.xml
5 years ago
freelancer-theme-jekyll.gemspec
Add html-proofer script and related fixes
2 years ago
index.html
Getting rid of unnecessary posts loop
7 years ago
screenshot.png
add screenshot
7 years ago
style.css
Some corrections
7 years ago
